### ISSUE TITLE
Playlists? Does this support them?

### ISSUE THREAD

**Issue by ghost** [sylc/ng2-youtube-player-mini#1]
I really love this package, what I'm missing with it though is the ability to pass a list of video ids in as a playlist?

Does this support it? Can it?

**Comment by sylc** [comment]
@nombiezinjas you cannot pass an array of videoId. However, i have just upgraded the repo to v 2.1.1 with a playlistId param. you could create a playlist on youtube and pass the playlistId. 
please note the change in the import statement.

**Comment by ghost** [comment]
Perfect!
